[project]
name = "nfl-fourthdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nfl-data-py>=0.3.3",
    "pandas>=1.5.3",
    "pyarrow>=21.0.0",
    "rpy2>=3.6.4",
]
